config/routes.rb
Nomster2::Application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photo2s, only: :create
  end
  resources :users, only: :show
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
	after_create :send_comment_email

	RATINGS = {
		'one star'   => '1_star',
		'two stars'   => '2_stars',
		'three stars' => '3_stars',
		'four stars'  => '4_stars',
		'five stars'  => '5_stars',
	}

	def humanized_rating
		RATINGS.invert[self.rating]
	end

	def send_comment_email
		NotificationMailer.comment_added(self).deliver
	end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
end

app/models/photo2.rb
class Photo2 < ActiveRecord::Base
	belongs_to :place
	mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :photo2s

	
	geocoded_by :address
  	after_validation :geocode
  	
	# used to be --> validates :name, presence: true
	validates :name, :address, :description, presence: true
	validates :name, length: { minimum: 3, :allow_blank => true , too_short: "Name must have at least 3 characters!" }

    # alternative
    #validates :name, presence: true, length: { minimum: 3, :allow_blank => true , too_short: "Name must have at least 3 characters!" }
    #validates :address, :description, presence: true

 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :places
  has_many :comments
  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(user: current_user))
		redirect_to place_path(@place)
	end

	private

	def comment_params
		params.require(:comment).permit(:message, :rating)
	end

end

app/controllers/photo2s_controller.rb
class Photo2sController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@place = Place.find(params[:place_id])
		@place.photo2s.create(photo2_params)
		redirect_to place_path(@place)
	end

	def photo2_params
		params.require(:photo2).permit(:caption, :picture)
	end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def new
	end

	def create
		@place = Place.find(params[:place_id])
		@photo = @place.photos.create(photo_params)
		#redirect_to place_path(@place)
	end

	private

	def photo_params
		params.require(:photo).permit(:picture, :caption)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		# see https://github.com/mislav/will_paginate
		# @places = Place.all
		# @places = Place.paginate(:page => params[:page])
		@places = Place.paginate(:page => params[:page], :per_page => 3)
	end

	def new
		@place = Place.new

	end

	def create
		# used to be --> Place.create(place_params)
		# used to be ---> current_user.places.create(place_params) add a var
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
		
	end

	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@photo2 = Photo2.new
		
	end

	def edit
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render text: 'Not Allowed, Dude. Stop it--Not Cool.', status: :forbidden
			# want to use 'not_acceptable'
		end
	end

	def update
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render text: 'Not Allowed, Dude. Not Cool.', status: :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render text: "Not Allowed. Can't do this", status: :forbidden
		end
		@place.destroy
		redirect_to root_path
	end




	private

	def place_params
		params.require(:place).permit(:name, :description, :address)
	end

	



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photo2s_helper.rb
module Photo2sHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Nomster-Rochebox-Great-Restaurants!</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-inverse no-bottom-margin" role="navigation">
			<div class="container-fluid">

				<!-- they note: brand and toggle grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>!
					
					<!-- below is a ruby link replacing this...an html A tag -->
					<%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
				</div>

				<!--Ken cuts it down a lot from the Twitter Bootstrap Model -->
				<!-- Note is Collect Nav Links, fore and stuff for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							
							 <%= link_to new_place_path do %>
   							 	<i class="glyphicon glyphicon-plus-sign"></i>
  							 	 <span class="nav-sign-in-fonts nomster-text-font"> New Place </span>
  							 	 <i class="glyphicon glyphicon glyphicon-eye-open"></i>
  							 	 <i class="glyphicon glyphicon-glass"></i>
  							 	 <i class="glyphicon glyphicon-star"></i>
 							 <% end %>
						</li>	
					</ul> <!-- nav navbar-nav -->

					<ul class="nav navbar-nav navbar-right">
						<% if user_signed_in? %>
						   <li>
	                            <%= link_to user_path(current_user) do %>
	                            <span class="nav-sign-in-fonts nomster-text-font">
	                            	My Profile</span>
	                            	<i class="glyphicon glyphicon-user"></i>
								<% end %>
							</li>
       						 <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete , class: 'nav-sign-in-fonts nomster-text-font' %></li>
     					 <% else %>
       						 <li><%= link_to 'Sign in', new_user_session_path , class: 'nav-sign-in-fonts nomster-text-font' %></li>
       						 <li><%= link_to 'Sign up', new_user_registration_path, class: 'nav-sign-in-fonts nomster-text-font' %></li>
      					<% end %>
						<!--li class="active"><a href="http://canadiens.nhl.com/">Link</a></li-->
					</ul> <!--nav navbar-nav navbar-right-->
				</div> <!-- collapse navbar collapse...-->
			</div>	<!-- "container fluid... div" ends-->
		</nav>

		<% if notice.present? %>
			<p class="alert alert-info col-xs-8 col-xs-offset-2"><%= notice %></p>
		<% end %>

		<% if alert.present? %>
			<p class="alert alert-danger col-xs-8 col-xs-offset-2"><%= alert %></p>
		<% end %>

		<%= yield %>

	</body>
</html>

app/views/places/edit.html.erb
<!-- view for editing a place entry -->
<div class="booyah-box col-xs-8 col-xs-offset-2">
  <h1 class="brand-font light-blue-color text-shadow-blue heading-size">Make a change -- Edit Your Place!</h1>

 
  <%= simple_form_for @place do |f| %>
    <div class="form-inputs form-styles nomster-text-font">
      	<%= f.input :name %>
    	<%= f.input :address %>
    	<%= f.input :description %>
    </div>
    	<br />
    <div class="form-actions">
    	<%= f.submit 'Update', class: 'btn btn-primary btn-lg nomster-button-styles nomster-text-font' %>
    </div>
	<% end %>
</div>

app/views/places/index.html.erb
<!-- Twitter Bootstrap Carousel Tags and styling -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>  
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">

  	<!-- slider 1 -->
    <div class="item active ">
      <%= image_tag 'lobster1_ready.jpg', class: 'img-responsive' %>
      <!--div class="carousel-caption nomster-text-font-not-bold"-->
      <div class="carousel-caption nomster-text-jinky grey-caption-color">
        Find Amazing Dishes!!!
      </div>
    </div>

	<!-- slider 2 -->
    <div class="item ">
      <%= image_tag 'bread_ready_2200px.jpg', class: 'img-responsive' %>
     <!--div class="carousel-caption nomster-text-font-not-bold"-->
     <div class="carousel-caption nomster-text-jinky grey-caption-color">
        Great cuisine!!!
      </div>
    </div>

	<!-- slider 3 -->
    <div class="item ">
      <%= image_tag 'great_chefs_ready.jpg', class: 'img-responsive' %>
      <!--div class="carousel-caption nomster-text-font-not-bold"-->
      <div class="carousel-caption nomster-text-jinky grey-caption-color">
        Amazing chefs!!!
      </div>
    </div>
    
    <!-- slider 4 -->
    <div class="item ">
      <%= image_tag 'slider1pano.jpg', class: 'img-responsive' %>
      <!--div class="carousel-caption nomster-text-font-not-bold"-->
      <div class="carousel-caption nomster-text-jinky grey-caption-color">
        Great restaurants!!!
      </div>
    </div>

   <!-- slider 5 -->
    <div class="item ">
      <%= image_tag 'donuts1_ready.jpg', class: 'img-responsive' %>
      <!--div class="carousel-caption nomster-text-font-not-bold"-->
      <div class="carousel-caption nomster-text-jinky grey-caption-color">
        All that is crazy good!!!
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>



<!-- code to display a listing of the places  from early Nomster lessons -->
<% @places.each do |place| %>
	<div class="booyah-box col-xs-8 col-xs-offset-2">
		<!-- h1 class="restaurant" -->
    <h1>
      <%= link_to place.name, place_path(place), :class => 'brand-font light-blue-color text-shadow-blue restaurant-link-styles' %>
    </h1> 
		<i class="index-place nomster-text-font"><%= place.address %></i>
    <br /><br />
		<p class="index-description index-indent"><%= place.description %></p><br />

		 <% if place.user.present? %>
        <div class="light-blue-color-2 nomster-text-font index-indent">
         <i class="glyphicon glyphicon-pencil"> </i>
     		 <small ><%= place.user.email %></small>
        </div>
   		 <% end %>
   		 <% if place.comments.present? %>
   		 	<div class="col-xs-12 ">
				  <blockquote class="sm-grow">
				  	
				    <% if place.comments.order("id ASC").last.humanized_rating.present? %>
				      <b><%= place.comments.order("id ASC").last.humanized_rating %></b> -
				    <% end %>
				   
				    <%= place.comments.order("id ASC").last.message %>
				   
				    <small><%= place.comments.order("id ASC").last.user.email %></small>
				  </blockquote>
			</div>
		<% end %>	
	</div>

	
<% end %>

<div class="col-xs-8 col-xs-offset-2 brand-font">
<%= will_paginate @places, renderer: BootstrapPagination::Rails %>
</div>

app/views/places/index.html2_exp_carousel.erb
<!-- Twitter Bootstrap Carousel Tags and styling -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">

  	<!-- slider 1 -->
    <div class="item active ">
      <%= image_tag 'slider1pano.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Find Amazing Dishes!!!
      </div>
    </div>

	<!-- slider 2 -->
    <div class="item ">
      <%= image_tag 'slider2pano.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Great cuisine!!!
      </div>
    </div>

	<!-- slider 3 -->
    <div class="item ">
      <%= image_tag 'slider3pano.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Amazing chefs!!!
      </div>
    </div>
    
    <!-- slider 4 -->
    <div class="item ">
      <%= image_tag 'slider6.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Great restaruants!!!
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<div class="clear-it"><br /></div>

<div class="col-md-12 ">
    <div class="carousel slide" id="myCarousel">
      <div class="carousel-inner">
        <div class="item active">
          <div class="col-xs-3">
              <%= image_tag 'slider1.jpg', class: 'img-responsive' %>
              <div class="carousel-caption">
                Find Amazing Dishes!!!
              </div>
          </div>
        </div>
        <div class="item">
          <div class="col-xs-3">
             <%= image_tag 'slider2.jpg', class: 'img-responsive' %>
              <div class="carousel-caption">
                Great cuisine!!!
              </div>
          </div>
        </div>
        <div class="item">
          <div class="col-xs-3"><a href="#"><img src="http://placehold.it/500/eeeeee&amp;text=3" class="img-responsive"></a></div>
        </div>
        <div class="item">
          <div class="col-xs-3"><a href="#"><img src="http://placehold.it/500/f4f4f4&amp;text=4" class="img-responsive"></a></div>
        </div>
        <div class="item">
          <div class="col-xs-3"><a href="#"><img src="http://placehold.it/500/f566f5/333&amp;text=5" class="img-responsive"></a></div>
        </div>
        <div class="item">
          <div class="col-xs-3"><a href="#"><img src="http://placehold.it/500/f477f4/fff&amp;text=6" class="img-responsive"></a></div>
        </div>
        <div class="item">
          <div class="col-xs-3"><a href="#"><img src="http://placehold.it/500/eeeeee&amp;text=7" class="img-responsive"></a></div>
        </div>
        <div class="item"
          <div class="col-xs-3"><a href="#"><img src="http://placehold.it/500/fcfcfc/333&amp;text=8" class="img-responsive"></a></div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
    </div>
</div>


<!-- code to display a listing of the places  from early Nomster lessons -->
<% @places.each do |place| %>
	<div class="booyah-box col-xs-8 col-xs-offset-2">
		<h1 class="restaurant"><%= link_to place.name, place_path(place) %></h1> 
		<i><%= place.address %></i><br /><br />
		<p><%= place.description %></p><br />

		 <% if place.user.present? %>
     		 <small><%= place.user.email %></small>
   		 <% end %>
   		 <% if place.comments.present? %>
   		 	<div class="col-xs-12 ">
				  <blockquote class="sm-grow">
				  	
				    <% if place.comments.order("id ASC").last.humanized_rating.present? %>
				      <b><%= place.comments.order("id ASC").last.humanized_rating %></b> -
				    <% end %>
				   
				    <%= place.comments.order("id ASC").last.message %>
				   
				    <small><%= place.comments.order("id ASC").last.user.email %></small>
				  </blockquote>
			</div>
		<% end %>	
	</div>

	
<% end %>

<div class="col-xs-8 col-xs-offset-2 brand-font">
<%= will_paginate @places, renderer: BootstrapPagination::Rails %>
</div>

app/views/places/new.html.erb
<!-- its the form page for a new place entry-->

<div class="booyah-box col-xs-8 col-xs-offset-2">
  <h1 class="brand-font light-blue-color text-shadow-blue heading-size">Enter Your Place Details...Here!</h1>

		 <div class="form-inputs form-styles nomster-text-font">
		  <%= simple_form_for @place do |f| %>
		      	<%= f.input :name %>
		    	<%= f.input :address %>
		    	<%= f.input :description %>
		    	<br />
		    	<%= f.submit 'Create', class: 'btn btn-primary btn-lg nomster-button-styles' %>
		  <% end %>
		</div>

</div>

app/views/places/show.html.erb
<!--This is the view from the "show" controller action from Lesson 21 -->
<!-- this shows the full record of the place (restaurant) -->

<div class="booyah-box col-xs-8 col-xs-offset-2">
	<h1 class="brand-font light-blue-color text-shadow-blue heading-size"><%= @place.name %></h1>
	<i class="index-place nomster-text-font"><%= @place.address %></i>
	<br/><br/>
	<p class="index-description index-indent"><%= @place.description %></p>
    <br />


    <!--  THIS IS THE PHOTO SECTION -->
	<div class="clear"></div>
		<% @place.photo2s.each do |phot| %>
			<div class="float-it col-xs-4">
				<div class="photo-box">
					<%= image_tag phot.picture , :class => "photo-box2" %>
					<p class="center-it photo-caption nomster-text-font"><%= phot.caption %></p>
				</div>	
			</div>
		<% end %>
	<br />
	<!--THIS IS THE MAP PART -->
	<div class="clear"></div>
	<!--here come the tags to place a google map Lesson 30 -->
	<% if @place.latitude.present? && @place.longitude.present? %>
		    <script>

		      function initMap() {
		        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

		        var map = new google.maps.Map(document.getElementById('map'), {
		          zoom: 14,
		          center: myLatLng
		        });

		        var marker = new google.maps.Marker({
		          position: myLatLng,
		          map: map,
		          title: 'Hello World!'
		        });
		      }
		    </script>
		    <script async defer
		    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzSJ-karImYqxutzcv3rCOwtyL7VCy2pk&callback=initMap">
		    </script>

		    <!-- moved from top in example... -->
			<div id="map"></div>
<% end %>

<br />

	<div class="pull-right">
		<% if current_user && current_user == @place.user %>
		<!-- Button trigger modal -->
		<button class="btn btn-primary btn-lg nomster-button-styles nomster-text-font" data-toggle="modal" data-target="#myModalPhoto">
		  Add a Photo!
		</button>
		

   		 <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary btn-lg nomster-button-styles nomster-text-font' %>
   		  <%= link_to 'Delete', place_path(@place), method: :delete, data: { confirm: 'Are you completely sure you want to delete this restaurant?'}, class: 'btn btn-danger btn-lg nomster-button-styles-delete nomster-text-font' %>
   		<% end %>
   		
    </div>
	<!--going to extend the booyah box ...it used to end here /div -->

	<div class="clear"></div>


<!-- Modal FOR ADD A PHOTO-->
<div class="modal fade" id="myModalPhoto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <!-- modal title -->
        <h2 class="brand-font red-color text-shadow-blue" id="myModalLabel">Add a Photo Here!</h2>
      </div >
     
			<%= simple_form_for @photo2, url: place_photo2s_path(@place) do |phot| %>
				<div class="modal-body nomster-text-font red-color">
			 		 <%= phot.input :picture %>
			 		 <%= phot.input :caption %>
     			 </div>

      <div class="modal-footer">
        	<button type="button" class="btn btn-default btn-lg nomster-text-font nomster-button-styles-close" data-dismiss="modal">
        		Close
        	</button>
           <%= phot.submit "Add Photo", class: 'btn btn-primary btn-lg nomster-text-font nomster-button-styles' %>
      </div>
   	<% end %>
    </div>
  </div>
</div>



	<!-- Modal for COMMENTS!!-->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
   	 <div class="modal-content">
    	<!-- working here... -->	
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <!-- modal title -->
	        <h2 class="brand-font red-color text-shadow-blue" id="myModalLabel">Add your comment!</h2>
	      </div>
     
 		<!-- I think this is where the really meat for the comments go... -->
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body nomster-text-font red-color"> 
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
         
     	 </div>
      	<div class="modal-footer">
         <button type="button" class="btn btn-default nomster-text-font nomster-button-styles-close" data-dismiss="modal">
         	Close
         </button>
         <%= f.submit "Add a Comment", class: 'btn btn-primary nomster-text-font nomster-button-styles' %>
      	</div>
     <% end %>
    </div>
  </div>
</div>
<!-- booyah div -->	
</div> 
<br />
<br />

<!--  HERE IS THE COMMENT PART -->
<div class="col-xs-12 ">
	<div class="col-xs-8 col-xs-offset-2" >
		<!-- h1 class="pull-left restaurant" -->
		<h1 class="text-center brand-font red-color text-shadow-blue pull-left">Comments</h1>
		
		<!-- Button trigger modal for comments -->
		<button class="btn btn-primary btn-lg nomster-button-styles nomster-text-font pull-right" data-toggle="modal" data-target="#myModal">
		  Add your comment!
		</button>
	</div>
	
</div>
<div class="clear"></div>
<% @place.comments.each do |comment| %>
	<div class ="col-xs-12 col-sm-6">
		<blockquote class="sm-grow">
			<% if comment.humanized_rating.present? %>
				<b><%= comment.humanized_rating %></b> -
			<% end %>	
			<%= comment.message %>
			<small><%= comment.user.email %></small>
		</blockquote>
	</div>
<% end %>